### ISSUE TITLE
Erroneous values against "first" & "last" aggregation-function in group-aggregate query's response

### ISSUE THREAD

**Issue by sviewni** [akumuli/Akumuli#357]
For the case when a metric's values are from some monotonically increasing function, I expected that "last" & "first" aggregation values should be equal to "min" & "max" aggregation values respectively. However, not just these values vary unexpectedly in certain aggregation steps, there is significant difference when comparing "first-last" with "max-min" in such instances. This is observed in roughly half of the total aggregation steps .

Code to recreate, https://github.com/sviewni/group-aggregate-test/blob/master/groupAggregateTest.js.

Versions:
akumuli/akumuli:0.8.79-skylake
DIGEST:sha256:c80a5d897223b3f638228f6cbbc559dd3ca9ba7b21e653a8ec9cf627d5452cd5
akumuli/akumuli:0.8.79-generic
DIGEST:sha256:fb241743dc4b1c926f0013a7b09bf5a6c05c15720b1503ce40850b3a0bd4dfa0

Thanks you for releasing the *0.8.79-* docker images.

**Comment by Lazin** [comment]
What version are you comparing to? Is it 0.8.75 or earlier?

**Comment by sviewni** [comment]
I checked using docker images only. Issue observed on both versions, akumuli/akumuli:0.8.79-skylake & 0.8.75.

**Comment by Lazin** [comment]
I merged the fix for that in #358 

The problem was caused by the inconsistency in behavior of first/last and first_timestamp/last_timestamp functions. The *_timestamp functions always returned data independently of scan direction (first_timestamp < last_timestamp) but first and last depend on scan direction. In your code, if you change it to scan forward ("to" is greater than the "from" field in the query) `first` will always be smaller than the `last`. But because you scan backward, `first` is larger than the `last`.

The problem with this is that it's impossible to fix without changing behavior because group-aggreagate results are not composable. So I changed behavior slightly. Now `first` and `last` functions doesn't depend on direction (the same way as `first_timestamp` and `last_timestamp`). `first` always return the first value in the bin chronologically and the `last` always return the last value in the bin, no matter in which direction are you scanning.

In your code you need to change one line and compute last-first instead of first-last.

**Comment by sviewni** [comment]
Thanks for this fix and explaining the cause.

I'm still not able to reason the previous behaviour, even if `first` and `last` were dependent on the scan direction, then should have been just interchanged (and my test program would pass). However, it had further inconsistency because of which roughly half of the bins had inaccurate difference between `first` & `last`. I'm not sure if it is due to 'composable' aspect mentioned by you.

I hope this change doesn't break other clients employing backward scan with assumptions originating from previous behaviour.

**Comment by Lazin** [comment]
There was a bug in the group-aggregate implementation, in the component that was used to glue several aggregates together. The aggregate is a struct with fields like min/max/sum/count etc (all composable aggregates), the first/last values and timestamps are also in the struct. The struct had no way to decide how to merge first and last values because it doesn't know the direction of the scan. It doesn't know it because it's also used for aggregate query which don't have the notion of direction. So as a bonus group-aggregate aggregate behaves consistently with aggregate query now.

**Comment by sviewni** [comment]
Now I understand it better. Thanks.
